<?php

namespace App\Modules\Role\Database\Factories;

use App\Modules\Role\Models\Role;
use Illuminate\Database\Eloquent\Factories\Factory;

class RoleFactory extends Factory
{
    protected $model = Role::class;

    public function definition(): array
    {
        $roleNames = [
            'Admin',
            'Manager',
            'User',
            'Guest',
            'Editor',
            'Moderator',
            'Supervisor',
            'Developer',
            'Designer',
            'Analyst',
            'Coordinator',
            'Specialist',
            'Assistant',
            'Director',
            'Lead',
            'Senior',
            'Junior',
            'Intern',
            'Consultant',
            'Expert',
            'Administrator',
            'Operator',
            'Technician',
            'Engineer',
            'Architect',
            'Planner',
            'Reviewer',
            'Auditor',
            'Inspector',
            'Controller',
            'Supervisor',
            'Coordinator',
            'Facilitator',
            'Liaison',
            'Representative',
            'Ambassador',
            'Advocate',
            'Champion',
            'Mentor',
            'Coach',
            'Trainer',
            'Instructor',
            'Teacher',
            'Professor',
            'Lecturer',
            'Researcher',
            'Scientist',
            'Investigator',
            'Explorer',
            'Pioneer',
            'Innovator',
            'Creator',
            'Founder',
            'Builder',
            'Maker',
            'Craftsman',
            'Artisan',
            'Artist',
            'Writer',
            'Author',
            'Blogger',
            'Journalist',
            'Reporter',
            'Correspondent',
            'Photographer',
            'Videographer',
            'Producer',
            'Director',
            'Editor',
            'Curator',
            'Librarian',
            'Archivist',
            'Historian',
            'Biographer',
            'Genealogist',
            'Anthropologist',
            'Sociologist',
            'Psychologist',
            'Therapist',
            'Counselor',
            'Advisor',
            'Consultant',
            'Mediator',
            'Negotiator',
            'Arbitrator',
            'Judge',
            'Lawyer',
            'Attorney',
            'Advocate',
            'Prosecutor',
            'Defender',
            'Guardian',
            'Protector',
            'Defender',
            'Champion'
        ];

        return [
            'name' => $this->faker->randomElement($roleNames) . ' ' . $this->faker->numberBetween(1, 999),
            'guard_name' => 'api',
        ];
    }
}
